### ISSUE TITLE
Docker image is always pulling even if build documentation step is conditional and inactive

### ISSUE THREAD

**Issue by VladimirRybalko** [nikeee/docfx-action#14]
I have the below step in my workflow.

```
- name: Build Documentation
   if: ${{ github.ref_name == 'master' && github.event_name == 'push' }}
   uses: nikeee/docfx-action@v1.0.0
   with:
     args: docs/docfx.json
```

As you see the step is conditional, however docker image is always pulling independently on step status.

This is what see in workflow logs:
![Screenshot 2022-01-05 at 17 10 23](https://user-images.githubusercontent.com/19630921/148250400-e1aaa372-82de-48c5-8362-9e047f35a732.png)

It's definitely not good. It takes 30 seconds every time for nothing even if docfx is not needed.
